src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER, options: ['unsigned' => true])]
    private ?int $id = null;

    #[ORM\Column(length: 160)]
    private ?string $title = null;

    #[ORM\Column(length: 162,unique: true)]
    private ?string $titleSlug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $text = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE,options: ["default" => "CURRENT_TIMESTAMP"])]
    private ?\DateTimeInterface $articleDateCreate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $articleDatePosted = null;

    #[ORM\Column(type: Types::BOOLEAN, options: ['default' => false])]
    private ?bool $published = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    /**
     * @var Collection<int, Section>
     */
    #[ORM\ManyToMany(targetEntity: Section::class, inversedBy: 'articles')]
    private Collection $sections;

    public function __construct()
    {
        $this->sections = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getTitleSlug(): ?string
    {
        return $this->titleSlug;
    }

    public function setTitleSlug(string $titleSlug): static
    {
        $this->titleSlug = $titleSlug;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): static
    {
        $this->text = $text;

        return $this;
    }

    public function getArticleDateCreate(): ?\DateTimeInterface
    {
        return $this->articleDateCreate;
    }

    public function setArticleDateCreate(\DateTimeInterface $articleDateCreate): static
    {
        $this->articleDateCreate = $articleDateCreate;

        return $this;
    }

    public function getArticleDatePosted(): ?\DateTimeInterface
    {
        return $this->articleDatePosted;
    }

    public function setArticleDatePosted(?\DateTimeInterface $articleDatePosted): static
    {
        $this->articleDatePosted = $articleDatePosted;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): static
    {
        $this->published = $published;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection<int, Section>
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): static
    {
        if (!$this->sections->contains($section)) {
            $this->sections->add($section);
        }

        return $this;
    }

    public function removeSection(Section $section): static
    {
        $this->sections->removeElement($section);

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Article;
use App\Entity\Section;


class MainController extends AbstractController
{
    #[Route('/', name: 'homepage')]
    public function index(EntityManagerInterface $em): Response
    {
        $categories = $em->getRepository(Section::class)->findAll();
        $articles = $em->getRepository(Article::class)->findBy(['published'=>true], ['articleDatePosted' => 'DESC'], 10);
        return $this->render('main/index.html.twig', [
            // on envoie les catégories à la vue
            'categories' => $categories,
            // on envoie les articles à la vue
            'articles' => $articles,
        ]);
    }
    #[Route('/categorie/{slug}', name: 'categorie')]
    public function categorie($slug, EntityManagerInterface $entityManager): Response
    {
        // récupération de toutes les catégories pour le menu
        $categories = $entityManager->getRepository(Section::class)->findAll();
        // récupération de la catégorie dont le slug est $category_slug
        $categorie = $entityManager->getRepository(Section::class)->findOneBy(['sectionSlug' => $slug]);
        // récupération des articles de la catégorie grâce à la relation ManyToMany de categorie vers articles puis prises de valeurs
        $articles = $entityManager->createQueryBuilder()
            ->select('a')
            ->from(Article::class, 'a')
            ->join('a.sections', 's') // Assurez-vous que 'sections' est le bon nom de la relation
            ->where('a.published = :published')
            ->andWhere('s.id = :categoryId')
            ->setParameter('published', true)
            ->setParameter('categoryId', $categorie->getId())
            ->orderBy('a.articleDatePosted', 'DESC')
            ->getQuery()
            ->getResult();

        return $this->render('main/categorie.html.twig', [
            // on envoie la catégorie à la vue
            'categories' => $categories,
            'categorie' => $categorie,
            'articles' => $articles,
        ]);
    }

    #[Route('/article/{slug}', name: 'article', methods: ['GET', 'POST'])]
    public function article($slug, EntityManagerInterface $entityManager): Response
    {
        // récupération de toutes les catégories pour le menu
        $categories = $entityManager->getRepository(Section::class)->findAll();
        // récupération de l'article dont le slug est $slug
        $article = $entityManager->getRepository(Article::class)->findOneBy(['titleSlug' => $slug]);


        return $this->render('main/article.html.twig', [
            'categories' => $categories,
            'article' => $article,
        ]);
    }
}

templates/main/article.html.twig
{% extends 'public.template.html.twig' %}

{% block title %}{{ parent() }} Article | {{ article.title }}{% endblock %}

{% block menuLinks %}
    {% include 'main/menu.html.twig' %}
{% endblock %}
{% block sizeTitle %}8{% endblock %}
{%block htitle %}Article : {{ article.title }}{% endblock %}
{%block hdesc %}{% endblock %}
{% block boutonshauts %}{% endblock %}

{% block articlePerOne %}

    <div class="col-lg-12 mb-5 mb-lg-0">
        <h2 class="h4 fw-bolder mb-3">{{ article.title }}</h2>
        <h4 class="h5">{{ article.User.fullname }} le {{ article.articleDatePosted|date("d/m/Y \à H:i") }}</h4>
        <hr>
        {% for section in article.sections %}
            {% if loop.first %}<p>Sections: {% endif %}
            <a href="{{ path("categorie", { 'slug' :  section.sectionSlug }) }}">{{ section.sectionTitle }}</a>
            {% if not loop.last %} | {% endif %}
            {% if loop.last %}</p>{% endif %}
        {% else %}
            <p>Pas de section</p>
        {% endfor %}
        <hr>
        <p>{{ article.text|striptags|nl2br }}</p>
        <h4 class="h5">Par {{ article.user.fullname }} le {{ article.articleDatePosted|date("d/m/Y \à H:i") }}</h4>
    </div>
    {% block commentaire %}{% endblock %}
{% endblock %}

templates/main/categorie.html.twig
{% extends 'public.template.html.twig' %}

{% block title %}{{ parent() }} Catégorie | {{ categorie.sectionTitle }}{% endblock %}

{% block menuLinks %}

    {% include 'main/menu.html.twig' %}
{% endblock %}
{% block sizeTitle %}8{% endblock %}
{%block htitle %}Catégorie : {{ categorie.sectionTitle }}{% endblock %}
{%block hdesc %}{{ categorie.sectionDetail }}{% endblock %}
{% block boutonshauts %}{% endblock %}


{% block articlePerOne %}
    {% for article in articles %}
        {% if article.published %}
            <div class="col-lg-4 mb-5 mb-lg-0">
                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-collection"></i></div>
                <h2 class="h4 fw-bolder">{{ article.Title }}</h2>
                <p>{{ article.User.fullname }} le {{ article.articleDatePosted|date("d/m/Y \à H:i") }}</p>
                {% for section in article.sections %}
                    {% if loop.first %}<p>Sections: {% endif %}
                    <a href="{{ path("categorie", { 'slug' :  section.sectionSlug }) }}">{{ section.sectionTitle }}</a>
                    {% if not loop.last %} | {% endif %}
                    {% if loop.last %}</p>{% endif %}
                {% else %}
                    <p>Pas de section</p>
                {% endfor %}
                <p>{{ article.Text|u.truncate(200, '...', false)|striptags }}</p>

                <a class="text-decoration-none" href="{{ path("article", { 'slug' :  article.titleSlug }) }}">
                    Lire la suite
                    <i class="bi bi-arrow-right"></i><p></p>
                </a>
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}

templates/main/index.html.twig
{% extends 'public.template.html.twig' %}

{% block title %}{{ parent() }} Page d'accueil{% endblock %}

{% block menuLinks %}
    {% include 'main/menu.html.twig' %}
{% endblock %}

{%block htitle %}Site TI minimal sur Symfony 6.4 LTS{% endblock %}
{%block hdesc %}Pour les webdevs du CF2m 2024{% endblock %}

{% block boutonshauts %}

{% endblock %}

{% block articlePerOne %}
    {% for article in articles %}
    <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-collection"></i></div>
        <h2 class="h4 fw-bolder">{{ article.Title }}</h2>
        <p>{{ article.User.fullname }} le {{ article.articleDatePosted|date("d/m/Y \à H:i") }}</p>
        {% for section in article.sections %}
            {% if loop.first %}<p>Sections: {% endif %}
            <a href="{{ path("categorie", { 'slug' :  section.sectionSlug }) }}">{{ section.sectionTitle }}</a>
            {% if not loop.last %} | {% endif %}
            {% if loop.last %}</p>{% endif %}
            {% else %}
            <p>Pas de section</p>
        {% endfor %}
        <p>{{ article.text|u.truncate(300, '...', false)|striptags }}</p>

        <a class="text-decoration-none" href="{{ path("article", { 'slug' :  article.titleSlug }) }}">
            Lire la suite
            <i class="bi bi-arrow-right"></i><p></p>
        </a>
    </div>
    {% endfor %}
{% endblock %}

templates/main/menu.html.twig
<li class="nav-item"><a class="nav-link" aria-current="page" href="{{ path('homepage') }}">Home</a></li>
{% for categ in categories %}
    <li class="nav-item"><a class="nav-link" aria-current="page"
                            href="{{ path("categorie", { 'slug' :  categ.sectionSlug }) }}">{{ categ.sectionTitle }}</a>
    </li>
{% endfor %}
    {% if is_granted("ROLE_USER") %}
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{ path('app_logout') }}">Déconnexion</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{ path('app_login') }}">Connexion</a>
        </li>

    {% endif %}
    {% if is_granted("ROLE_ADMIN") %}
        <li class="nav-item">
            <a class="nav-link" href="{{ path('admin') }}">Administration</a>
        </li>
    {% endif %}